set up osv-scanner reporting

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -44,10 +44,12 @@ jobs:
         path: ${{ runner.temp }}/candidate_image.tar
 
   osv_scan:
+    # see https://github.com/google/osv-scanner-action/blob/main/.github/workflows/osv-scanner-reusable.yml
     runs-on: ubuntu-latest # maintained by GitHub
+
     permissions:
-      contents: read
       actions: read
+      contents: read
       security-events: write
     needs: build_and_load
     steps:
@@ -66,8 +68,28 @@ jobs:
 
         docker load -i ${{ runner.temp }}/candidate_image.tar
 
-        osv-scanner scan image candidate_image:latest
-        
+        osv-scanner scan image candidate_image:latest --format=sarif --output=osv_scan_results.sarif
+
+    - name: Upload OSV scan results
+      id: upload_artifact
+      if: ${{ always() }}
+      uses: actions/upload-artifact@v4
+      with:
+        name: osv_scan_results_sarif
+        path: osv_scan_results.sarif
+        retention-days: 5
+
+    - name: Upload OSV scan results to Code Scanning
+      if: ${{ always() }}
+      uses: github/codeql-action/upload-sarif@v3
+      with:
+        sarif_file: osv_scan_results.sarif
+
+    - name: Check if artifact upload failed
+      if: ${{ always() && steps.upload_artifact.outcome == 'failure' }}
+      run: |
+        echo "::error::Artifact upload failed. This is most likely caused by a error during scanning earlier in the workflow."
+        exit 1
 
   image_test:
     runs-on: ubuntu-latest # maintained by GitHub
